# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'iOS-MVVM-Demo' do

pod 'ReactiveCocoa', '>= 2.4.4'
pod 'AFNetworking', '>= 2.5.1'

end

target 'iOS-MVVM-DemoTests' do

end

